version: '2'
services:

  nginx:
    restart: always
    container_name: crypto-api-nginx
    image: nginx:latest
    ports:
      - "8180:80"
    volumes:
      - ./src:/src
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    links:
      - php
    networks:
        docker0:
          external: true
          ipv4_address: 172.17.0.10

  php:
    restart: always
    container_name: crypto-api-php
    image: crypto/api/php
    build: docker/php
    volumes:
      - ./src:/src
      - ./logs/php:/logs
    env_file:
      - ./.env
    links:
      - memcached
    networks:
        docker0:
          external: true
          ipv4_address: 172.17.0.11

  memcached:
      restart: always
      container_name: crypto-api-memcached
      image: memcached:latest
      volumes:
        - ./logs/memcached/:/logs
      networks:
        docker0:
          external: true
          ipv4_address: 172.17.0.12